version: '3.8'

services:
  db:
    image: pgvector/pgvector:pg16
    container_name: time_series_db
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
      POSTGRES_DB: time_series
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./init:/docker-entrypoint-initdb.d

volumes:
  db_data:
